if(NOT DEFINED RKDEV_SEARCH_ROOT)
  message(FATAL_ERROR "RKDEV_SEARCH_ROOT not set")
endif()
if(NOT DEFINED RKDEV_BINARY_NAME)
  message(FATAL_ERROR "RKDEV_BINARY_NAME not set")
endif()
if(NOT DEFINED RKDEV_ALT_BINARY_NAME)
  set(RKDEV_ALT_BINARY_NAME "")
endif()
if(NOT DEFINED RKDEV_DEST_DIR)
  message(FATAL_ERROR "RKDEV_DEST_DIR not set")
endif()

if(DEFINED RKDEV_BASH AND EXISTS "${RKDEV_BASH}")
  if(NOT DEFINED RKDEV_MSYSTEM OR RKDEV_MSYSTEM STREQUAL "")
    set(RKDEV_MSYSTEM "MINGW64")
  endif()
  string(TOLOWER "${RKDEV_MSYSTEM}" RKDEV_MSYSTEM_LOWER)
  set(RKDEV_PATH_PREFIX "/${RKDEV_MSYSTEM_LOWER}/bin:/usr/bin")
  set(RKDEV_SEARCH_ROOT_POSIX "${RKDEV_SEARCH_ROOT}")
  execute_process(
    COMMAND ${RKDEV_BASH} -lc "cygpath -u \"${RKDEV_SEARCH_ROOT}\""
    OUTPUT_VARIABLE RKDEV_SEARCH_ROOT_POSIX
    RESULT_VARIABLE RKDEV_CYGPATH_RESULT
  )
  string(STRIP "${RKDEV_SEARCH_ROOT_POSIX}" RKDEV_SEARCH_ROOT_POSIX)
  if(NOT RKDEV_CYGPATH_RESULT EQUAL 0 OR RKDEV_SEARCH_ROOT_POSIX STREQUAL "")
    file(TO_CMAKE_PATH "${RKDEV_SEARCH_ROOT}" RKDEV_SEARCH_ROOT_POSIX)
  endif()

  set(RKDEV_FIND_EXPR "-name '${RKDEV_BINARY_NAME}'")
  if(RKDEV_ALT_BINARY_NAME)
    set(RKDEV_FIND_EXPR "\\( -name '${RKDEV_BINARY_NAME}' -o -name '${RKDEV_ALT_BINARY_NAME}' \\)")
  endif()

  execute_process(
    COMMAND ${RKDEV_BASH} -lc "export MSYSTEM=${RKDEV_MSYSTEM}; export PATH=${RKDEV_PATH_PREFIX}:$PATH; find \"${RKDEV_SEARCH_ROOT_POSIX}\" -type f ${RKDEV_FIND_EXPR} -print -quit"
    OUTPUT_VARIABLE RKDEV_FIND_OUT
    RESULT_VARIABLE RKDEV_FIND_RESULT
  )
  string(STRIP "${RKDEV_FIND_OUT}" RKDEV_FIND_OUT)
  if(RKDEV_FIND_RESULT EQUAL 0 AND NOT RKDEV_FIND_OUT STREQUAL "")
    execute_process(
      COMMAND ${RKDEV_BASH} -lc "cygpath -w \"${RKDEV_FIND_OUT}\""
      OUTPUT_VARIABLE RKDEV_SRC
      RESULT_VARIABLE RKDEV_CYGPATH_RESULT
    )
    string(STRIP "${RKDEV_SRC}" RKDEV_SRC)
    if(RKDEV_CYGPATH_RESULT EQUAL 0 AND NOT RKDEV_SRC STREQUAL "")
      message(STATUS "Using rkdeveloptool binary at ${RKDEV_SRC}")
      file(MAKE_DIRECTORY "${RKDEV_DEST_DIR}")
      execute_process(
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${RKDEV_SRC}" "${RKDEV_DEST_DIR}"
        RESULT_VARIABLE RKDEV_COPY_RESULT
      )
      if(NOT RKDEV_COPY_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to copy rkdeveloptool from '${RKDEV_SRC}' to '${RKDEV_DEST_DIR}'")
      endif()
      return()
    endif()
  endif()

  execute_process(
    COMMAND ${RKDEV_BASH} -lc "export MSYSTEM=${RKDEV_MSYSTEM}; export PATH=${RKDEV_PATH_PREFIX}:$PATH; find \"$HOME\" -type f ${RKDEV_FIND_EXPR} -print -quit"
    OUTPUT_VARIABLE RKDEV_HOME_FIND_OUT
    RESULT_VARIABLE RKDEV_HOME_FIND_RESULT
  )
  string(STRIP "${RKDEV_HOME_FIND_OUT}" RKDEV_HOME_FIND_OUT)
  if(RKDEV_HOME_FIND_RESULT EQUAL 0 AND NOT RKDEV_HOME_FIND_OUT STREQUAL "")
    execute_process(
      COMMAND ${RKDEV_BASH} -lc "cygpath -w \"${RKDEV_HOME_FIND_OUT}\""
      OUTPUT_VARIABLE RKDEV_SRC
      RESULT_VARIABLE RKDEV_CYGPATH_RESULT
    )
    string(STRIP "${RKDEV_SRC}" RKDEV_SRC)
    if(RKDEV_CYGPATH_RESULT EQUAL 0 AND NOT RKDEV_SRC STREQUAL "")
      message(STATUS "Using rkdeveloptool binary at ${RKDEV_SRC}")
      file(MAKE_DIRECTORY "${RKDEV_DEST_DIR}")
      execute_process(
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${RKDEV_SRC}" "${RKDEV_DEST_DIR}"
        RESULT_VARIABLE RKDEV_COPY_RESULT
      )
      if(NOT RKDEV_COPY_RESULT EQUAL 0)
        message(FATAL_ERROR "Failed to copy rkdeveloptool from '${RKDEV_SRC}' to '${RKDEV_DEST_DIR}'")
      endif()
      return()
    endif()
  endif()
endif()

set(RKDEV_CANDIDATES)
file(GLOB_RECURSE RKDEV_PRIMARY LIST_DIRECTORIES false
  "${RKDEV_SEARCH_ROOT}/${RKDEV_BINARY_NAME}"
)
list(APPEND RKDEV_CANDIDATES ${RKDEV_PRIMARY})
if(RKDEV_ALT_BINARY_NAME)
  file(GLOB_RECURSE RKDEV_ALT LIST_DIRECTORIES false
    "${RKDEV_SEARCH_ROOT}/${RKDEV_ALT_BINARY_NAME}"
  )
  list(APPEND RKDEV_CANDIDATES ${RKDEV_ALT})
endif()
list(LENGTH RKDEV_CANDIDATES RKDEV_COUNT)
if(RKDEV_COUNT EQUAL 0)
  get_filename_component(RKDEV_PARENT "${RKDEV_SEARCH_ROOT}" DIRECTORY)
  if(RKDEV_PARENT AND NOT RKDEV_PARENT STREQUAL RKDEV_SEARCH_ROOT)
    set(RKDEV_CANDIDATES)
    file(GLOB_RECURSE RKDEV_PRIMARY_PARENT LIST_DIRECTORIES false
      "${RKDEV_PARENT}/${RKDEV_BINARY_NAME}"
    )
    list(APPEND RKDEV_CANDIDATES ${RKDEV_PRIMARY_PARENT})
    if(RKDEV_ALT_BINARY_NAME)
      file(GLOB_RECURSE RKDEV_ALT_PARENT LIST_DIRECTORIES false
        "${RKDEV_PARENT}/${RKDEV_ALT_BINARY_NAME}"
      )
      list(APPEND RKDEV_CANDIDATES ${RKDEV_ALT_PARENT})
    endif()
  endif()
endif()
list(LENGTH RKDEV_CANDIDATES RKDEV_COUNT)
if(RKDEV_COUNT EQUAL 0)
  message(FATAL_ERROR "rkdeveloptool binary '${RKDEV_BINARY_NAME}' not found under '${RKDEV_SEARCH_ROOT}' or its parent")
endif()

list(SORT RKDEV_CANDIDATES)
list(GET RKDEV_CANDIDATES 0 RKDEV_SRC)
message(STATUS "Using rkdeveloptool binary at ${RKDEV_SRC}")

file(MAKE_DIRECTORY "${RKDEV_DEST_DIR}")
execute_process(
  COMMAND ${CMAKE_COMMAND} -E copy_if_different "${RKDEV_SRC}" "${RKDEV_DEST_DIR}"
  RESULT_VARIABLE RKDEV_COPY_RESULT
)
if(NOT RKDEV_COPY_RESULT EQUAL 0)
  message(FATAL_ERROR "Failed to copy rkdeveloptool from '${RKDEV_SRC}' to '${RKDEV_DEST_DIR}'")
endif()
